PRODUCT_VERSION_MAJOR = 24
PRODUCT_VERSION_MINOR = 0

ifeq ($(LINEAGE_VERSION_APPEND_TIME_OF_DAY),true)
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set LINEAGE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef LINEAGE_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "LINEAGE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^LINEAGE_||g')
        LINEAGE_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(LINEAGE_BUILDTYPE)),)
    LINEAGE_BUILDTYPE := UNOFFICIAL
    LINEAGE_EXTRAVERSION :=
endif

ifeq ($(LINEAGE_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        LINEAGE_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)$(LINEAGE_EXTRAVERSION)-$(LINEAGE_BUILD)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)

# LineageOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.lineage.version=$(LINEAGE_VERSION) \
    ro.lineage.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.lineage.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.lineage.releasetype=$(LINEAGE_BUILDTYPE)

# Yasvara version
YASVARA_VERSION_MAJOR := 1
YASVARA_VERSION_MINOR := 0

ifeq ($(WITH_GMS),true)
    YASVARA_VARIANT := GMS
else
    YASVARA_VARIANT := VANILLA
endif

YASVARA_VERSION := $(YASVARA_VERSION_MAJOR).$(YASVARA_VERSION_MINOR)-$(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)-$(YASVARA_VARIANT)-$(LINEAGE_BUILD)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.yasvara.version=$(YASVARA_VERSION) \
    ro.yasvara.build.version=$(YASVARA_VERSION_MAJOR).$(YASVARA_VERSION_MINOR) \
    ro.yasvara.variant=$(YASVARA_VARIANT) \
    ro.yasvara.releasetype=$(LINEAGE_BUILDTYPE) \
    ro.yasvara.base=lineage-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)
